[env]

[config]
default_to_workspace = false

[tasks.day-01-a]
command = "cargo"
args = ["run", "--bin", "day_01_a", "--", "input/01"]

[tasks.day-01-b]
command = "cargo"
args = ["run", "--bin", "day_01_b", "--", "input/01"]

[tasks.day-02-a]
command = "cargo"
args = ["run", "--bin", "day_02_a", "--", "input/02"]

[tasks.day-02-b]
command = "cargo"
args = ["run", "--bin", "day_02_b", "--", "input/02"]

[tasks.day-03-a]
command = "cargo"
args = ["run", "--bin", "day_03_a", "--", "input/03"]

[tasks.day-03-b]
command = "cargo"
args = ["run", "--bin", "day_03_b", "--", "input/03"]

[tasks.day-04-a]
command = "cargo"
args = ["run", "--bin", "day_04_a", "--", "input/04"]

[tasks.day-04-b]
command = "cargo"
args = ["run", "--bin", "day_04_b", "--", "input/04"]

[tasks.day-05-a]
command = "cargo"
args = ["run", "--bin", "day_05_a", "--", "input/05"]

[tasks.day-05-b]
command = "cargo"
args = ["run", "--bin", "day_05_b", "--", "input/05"]

[tasks.day-06-a]
command = "cargo"
args = ["run", "--bin", "day_06_a", "--", "input/06"]

[tasks.day-06-b]
command = "cargo"
args = ["run", "--bin", "day_06_b", "--", "input/06"]

[tasks.day-07-a]
command = "cargo"
args = ["run", "--bin", "day_07_a", "--", "input/07"]

[tasks.day-07-b]
command = "cargo"
args = ["run", "--bin", "day_07_b", "--", "input/07"]

[tasks.day-08-a]
command = "cargo"
args = ["run", "--bin", "day_08_a", "--", "input/08"]

[tasks.day-08-b]
command = "cargo"
args = ["run", "--bin", "day_08_b", "--", "input/08"]
